name:                haskell-database
version:             0.1.0.0
github:              "patryk-marcin-zielinski/haskell-database"
license:             BSD3
author:              "Patryk Zieliński"
maintainer:          "patrykzielu@gmail.com"
copyright:           "2018 Patryk Zieliński"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-database#readme>

dependencies:
- base >= 4.7 && < 5
- hasql
- persistent
#- esqueleto # used with persistent
#- squeal-postgresql
#- project-m36
#- beam-core
#- beam-postgres
#- opaleye
#- rel8 # used with opaleye
#- relational-record
#- HaskRel
#- HDBC

library:
  source-dirs: src

executables:
  haskell-database-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-database

tests:
  haskell-database-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-database
